#!/bin/bash
# Playwright — browser automation framework (Python CLI + Chromium browser).
#
# Self-contained installer: pulls its own Chromium runtime apt deps via
# `playwright install-deps chromium` (uses passwordless sudo). No entries
# in packages.txt needed — Playwright owns its dependency list.
#
# Installs:
#   - Dedicated venv at $TOOLS_DIR/uv-tools/playwright-venv (via `uv venv`)
#   - playwright (Python pkg) into that venv via `uv pip install`
#   - Wrapper at $TOOLS_BIN/playwright (self-healing browser-cache symlink)
#   - Chromium runtime apt deps via sudo `playwright install-deps chromium`
#   - Chromium browser binaries to a persistent cache dir under tools-cache volume
#
# Why a dedicated venv instead of `uv tool install`:
#   Playwright's wheel is tagged `py3-none-any` but actually bundles a 122 MB
#   platform-specific Node binary at `playwright/driver/node`. `uv tool install`
#   silently drops the entire `driver/` subtree during linking, leaving the CLI
#   broken with `FileNotFoundError: …/playwright/driver/node` on first
#   invocation. `uv pip install` into a plain venv copies all wheel contents
#   verbatim and works reliably.
#
# Persistence trick — wrapper-script approach:
#   Playwright (Python lib + Node @playwright/test) looks up browsers at the
#   default location $HOME/.cache/ms-playwright. We can't use the env var
#   PLAYWRIGHT_BROWSERS_PATH (would require ~/.zshrc.local — sometimes RO,
#   and wouldn't apply to Python tests that import playwright directly).
#   Solution: install a thin wrapper at $TOOLS_BIN/playwright that ensures
#   ~/.cache/ms-playwright is a symlink to the persistent browser cache
#   BEFORE invoking the real venv binary. This keeps the lookup correct even
#   after container recreation (writable layer wipe), since install.sh runs
#   `playwright --version` for cache verification at every entrypoint, which
#   invokes the wrapper, which restores the symlink.

set -e

INSTALL_BIN="${TOOLS_BIN:-$HOME/.cache/djinn-tools/bin}"
INSTALL_TOOLS="${TOOLS_DIR:-$HOME/.cache/djinn-tools}/uv-tools"
VENV_DIR="$INSTALL_TOOLS/playwright-venv"
BROWSERS_DIR="${TOOLS_DIR:-$HOME/.cache/djinn-tools}/playwright-browsers"
WRAPPER="$INSTALL_BIN/playwright"
REAL_BIN="$VENV_DIR/bin/playwright"

mkdir -p "$INSTALL_BIN" "$INSTALL_TOOLS" "$BROWSERS_DIR"

# Clean up artefacts from the previous `uv tool install` strategy so a stale
# tool symlink can't shadow the wrapper. Safe no-op on first run.
UV_TOOL_DIR="$INSTALL_TOOLS" UV_TOOL_BIN_DIR="$INSTALL_BIN" \
UV_PYTHON_INSTALL_DIR="$TOOLS_DIR/python" \
    uv tool uninstall playwright 2>/dev/null || true

# Fresh venv per install keeps the result deterministic and avoids stale
# state from interrupted previous runs.
rm -rf "$VENV_DIR"
UV_PYTHON_INSTALL_DIR="$TOOLS_DIR/python" \
    uv venv "$VENV_DIR" 2>&1 | tail -3

# `uv pip install` copies all wheel files, including the 122 MB
# `playwright/driver/node` binary that `uv tool install` silently drops.
UV_PYTHON_INSTALL_DIR="$TOOLS_DIR/python" \
    uv pip install --python "$VENV_DIR/bin/python" playwright 2>&1 | tail -3

# Install the self-healing wrapper. Wrapper ensures
# ~/.cache/ms-playwright is a symlink to BROWSERS_DIR on every invocation,
# so container recreation (which wipes the writable layer where
# ~/.cache/ms-playwright lives) is handled automatically.
rm -f "$WRAPPER"
cat > "$WRAPPER" <<WRAPPER_EOF
#!/bin/bash
# Auto-generated by tools/installers/playwright.sh — DO NOT EDIT.
# Self-healing wrapper: ensures \$HOME/.cache/ms-playwright -> persistent cache.
DEFAULT="\$HOME/.cache/ms-playwright"
TARGET="$BROWSERS_DIR"
if [[ ! -L "\$DEFAULT" ]] || [[ "\$(readlink "\$DEFAULT")" != "\$TARGET" ]]; then
    [[ -e "\$DEFAULT" ]] && rm -rf "\$DEFAULT"
    mkdir -p "\$(dirname "\$DEFAULT")"
    ln -sfn "\$TARGET" "\$DEFAULT"
fi
exec "$REAL_BIN" "\$@"
WRAPPER_EOF
chmod +x "$WRAPPER"

# Trigger wrapper once to establish the symlink before we install browsers/deps
"$WRAPPER" --version >/dev/null

# Install Chromium runtime apt deps using Playwright's canonical list
sudo "$WRAPPER" install-deps chromium

# Install Chromium browser binaries (idempotent — Playwright skips if present)
"$WRAPPER" install chromium

# Output version (last line — used as cache marker by tools/install.sh)
"$WRAPPER" --version
