#!/bin/bash
# pnpm via Corepack, with project packageManager pins respected by the wrappers.
#
# Install Corepack from npm into the tools cache volume: Node >= 25 no longer
# bundles it, and the shims `corepack enable` writes next to Node live in the
# container layer, which a new container discards. COREPACK_HOME also lives in
# the volume, preserving downloaded package managers and the known-good release
# for new containers. After an image rebuild, install.sh re-runs this installer
# like every other optional tool.
#
# Wrappers on $TOOLS_BIN set the cache default and call the volume's Corepack
# explicitly, independently of Corepack shims in the current Node installation.
set -e

TOOLS_DIR="${TOOLS_DIR:-$HOME/.cache/djinn-tools}"
INSTALL_DIR="${TOOLS_BIN:-$TOOLS_DIR/bin}"
COREPACK_PREFIX="$TOOLS_DIR/corepack"
COREPACK_HOME_DIR="$TOOLS_DIR/corepack-home"

mkdir -p "$INSTALL_DIR" "$COREPACK_HOME_DIR"

npm install --global --prefix "$COREPACK_PREFIX" corepack@latest --no-fund --no-audit >&2

# Stage each wrapper next to its target so it never replaces a working wrapper
# with a partially written file.
for name in pnpm pnpx; do
    staged=$(mktemp "$INSTALL_DIR/.$name.XXXXXX")
    cat > "$staged" <<EOF
#!/bin/sh
# Generated by tools/installers/pnpm.sh — do not edit; re-run the installer.
export COREPACK_HOME="\${COREPACK_HOME:-$COREPACK_HOME_DIR}"
exec "$COREPACK_PREFIX/bin/corepack" $name "\$@"
EOF
    chmod +x "$staged"
    mv "$staged" "$INSTALL_DIR/$name"
done

"$INSTALL_DIR/pnpm" --version
