#!/bin/bash
# Rust - toolchain via rustup (cargo, rustc, rustfmt, clippy)
# djinn-verify: cargo --version
#
# rustup and cargo live in the tools cache volume ($TOOLS_DIR/rustup and
# $TOOLS_DIR/cargo), so the toolchain, the crate registry cache and binaries
# from `cargo install` survive container restarts. Image rebuilds only re-run
# this script, which then updates instead of downloading everything again.
#
# The rustup proxies need RUSTUP_HOME and CARGO_HOME, which the image's shell
# setup does not know. Every binary in $CARGO_HOME/bin therefore gets a small
# wrapper on $TOOLS_BIN (already on PATH). After a later `cargo install`, run
# this script again to wrap the new binary.
#
# Optional environment:
#   RUST_TOOLCHAIN   toolchain to install and make default (default: stable)
#   RUST_COMPONENTS  extra components, comma-separated (e.g. rust-src,rust-analyzer)
set -e

TOOLS_DIR="${TOOLS_DIR:-$HOME/.cache/djinn-tools}"
INSTALL_DIR="${TOOLS_BIN:-$TOOLS_DIR/bin}"
RUST_TOOLCHAIN="${RUST_TOOLCHAIN:-stable}"
COMPONENTS="rustfmt,clippy${RUST_COMPONENTS:+,$RUST_COMPONENTS}"

export RUSTUP_HOME="$TOOLS_DIR/rustup"
export CARGO_HOME="$TOOLS_DIR/cargo"
RUSTUP="$CARGO_HOME/bin/rustup"

mkdir -p "$INSTALL_DIR" "$RUSTUP_HOME" "$CARGO_HOME"

# Same stall guards as sops.sh: abort a stalled transfer so --retry can start over.
CURL_GUARDS=(--proto '=https' --tlsv1.2 --connect-timeout 10 --retry 4 --retry-delay 3
             --speed-limit 2048 --speed-time 30)

if [[ ! -x "$RUSTUP" ]]; then
    # rustup-init straight from static.rust-lang.org, checked against its published
    # SHA-256 before it runs — no piped shell script.
    base="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu"
    tmp_dir=$(mktemp -d)
    trap 'rm -rf "$tmp_dir"' EXIT
    curl -fsSL "${CURL_GUARDS[@]}" "$base/rustup-init" -o "$tmp_dir/rustup-init"
    expected=$(curl -fsSL "${CURL_GUARDS[@]}" --max-time 30 "$base/rustup-init.sha256" | awk '{print $1}')
    actual=$(sha256sum "$tmp_dir/rustup-init" | awk '{print $1}')
    if [[ -z "$expected" || "$expected" != "$actual" ]]; then
        echo "rust: rustup-init checksum mismatch (expected '${expected}', got '${actual}')" >&2
        exit 1
    fi
    chmod +x "$tmp_dir/rustup-init"
    "$tmp_dir/rustup-init" -y --no-modify-path --profile minimal --default-toolchain none >&2
    rm -rf "$tmp_dir"
    trap - EXIT
else
    "$RUSTUP" self update >&2 || echo "rust: rustup self update failed, continuing with installed rustup" >&2
fi

"$RUSTUP" toolchain install "$RUST_TOOLCHAIN" --profile minimal --component "$COMPONENTS" >&2
"$RUSTUP" default "$RUST_TOOLCHAIN" >&2

# Wrap every binary in $CARGO_HOME/bin. Each wrapper is staged next to its target
# and moved into place, so a half-written wrapper never shadows a working one.
for target in "$CARGO_HOME"/bin/*; do
    [[ -f "$target" && -x "$target" ]] || continue
    name=$(basename "$target")
    staged=$(mktemp "$INSTALL_DIR/.$name.XXXXXX")
    cat > "$staged" <<EOF
#!/bin/sh
# Generated by tools/installers/rust.sh — do not edit; re-run the installer.
export RUSTUP_HOME="$RUSTUP_HOME"
export CARGO_HOME="$CARGO_HOME"
case ":\$PATH:" in
    *":$CARGO_HOME/bin:"*) ;;
    *) PATH="$CARGO_HOME/bin:\$PATH"; export PATH ;;
esac
exec "$CARGO_HOME/bin/$name" "\$@"
EOF
    chmod +x "$staged"
    mv "$staged" "$INSTALL_DIR/$name"
done

"$INSTALL_DIR/cargo" --version
