FROM golang:1.27.1-alpine AS build
ARG TARGETARCH
ARG TARGETVARIANT
WORKDIR /src
COPY helper/hostctl/ ./
RUN go test ./... && CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH:-amd64} GOARM=${TARGETVARIANT#v} go build -trimpath -ldflags="-s -w" -o /out/djinn-hostctl-supervisor .

FROM scratch
COPY --from=build /out/djinn-hostctl-supervisor /djinn-hostctl-supervisor
