"""Core utilities for AI Dev Base CLI."""

from ai_dev_base.core.decorators import handle_config_errors
from ai_dev_base.core.console import (
    blank,
    console,
    create_volume_table,
    err_console,
    error,
    header,
    info,
    print_volume_table,
    status_line,
    success,
    warning,
)
from ai_dev_base.core.docker import (
    ContainerOptions,
    RunResult,
    cleanup_docker_proxy,
    compose_build,
    compose_down,
    compose_run,
    compose_up,
    delete_volume,
    delete_volumes,
    ensure_network,
    get_compose_files,
    get_existing_volumes_by_category,
    get_running_containers,
    get_shell_mount_args,
    is_container_running,
    list_volumes,
    network_exists,
    volume_exists,
)
from ai_dev_base.core.paths import (
    AGENTS_FILE,
    CONFIG_DIR,
    CONFIG_FILE,
    get_config_dir,
    get_project_root,
    resolve_mount_path,
)

__all__ = [
    # Decorators
    "handle_config_errors",
    # Path utilities
    "CONFIG_DIR",
    "CONFIG_FILE",
    "AGENTS_FILE",
    "get_project_root",
    "get_config_dir",
    "resolve_mount_path",
    # Console utilities
    "console",
    "err_console",
    "status_line",
    "error",
    "success",
    "info",
    "warning",
    "blank",
    "header",
    "create_volume_table",
    "print_volume_table",
    # Docker utilities
    "ContainerOptions",
    "RunResult",
    "ensure_network",
    "network_exists",
    "get_compose_files",
    "get_shell_mount_args",
    "compose_build",
    "compose_run",
    "compose_up",
    "compose_down",
    "cleanup_docker_proxy",
    "is_container_running",
    "get_running_containers",
    "list_volumes",
    "volume_exists",
    "delete_volume",
    "delete_volumes",
    "get_existing_volumes_by_category",
]
